### ISSUE TITLE
recommended torch version may be wrong

### ISSUE THREAD

**Issue by RylonW** [microsoft/CvT#22]
After installing torch 1.7.1, I got an ERROR:
         ModuleNotFoundError: No module named 'torch.fx
What I find on stackoverflow is that **torch.fx was added in PyTorch 1.8.0.**, so may be recommended version is wrong?

**Comment by Mingbo-Lee** [comment]
I agree with you.
when I run following  command:
```bash
python -m pip install -r requirements.txt --user -q
```
```bash
bash run.sh  -t train --cfg experiments/imagenet/cvt/cvt-13-224x224.yaml
```
I got error:
```bash
Traceback (most recent call last):
  File "tools/train.py", line 28, in <module>
    from utils.utils import create_logger
  File "/home/limingbo/project/CvT/tools/../lib/utils/utils.py", line 18, in <module>
    from ptflops import get_model_complexity_info
  File "/home/limingbo/.local/lib/python3.7/site-packages/ptflops/__init__.py", line 10, in <module>
    from .flops_counter import FLOPS_BACKEND, get_model_complexity_info
  File "/home/limingbo/.local/lib/python3.7/site-packages/ptflops/flops_counter.py", line 15, in <module>
    from .aten_engine import get_flops_aten
  File "/home/limingbo/.local/lib/python3.7/site-packages/ptflops/aten_engine.py", line 17, in <module>
    from torch.utils._python_dispatch import TorchDispatchMode
ModuleNotFoundError: No module named 'torch.utils._python_dispatch'
```

**Comment by Mingbo-Lee** [comment]
> I agree with you. when I run following command:
> 
> python -m pip install -r requirements.txt --user -q
> bash run.sh  -t train --cfg experiments/imagenet/cvt/cvt-13-224x224.yaml
> I got error:
> 
> Traceback (most recent call last):
>   File "tools/train.py", line 28, in <module>
>     from utils.utils import create_logger
>   File "/home/limingbo/project/CvT/tools/../lib/utils/utils.py", line 18, in <module>
>     from ptflops import get_model_complexity_info
>   File "/home/limingbo/.local/lib/python3.7/site-packages/ptflops/__init__.py", line 10, in <module>
>     from .flops_counter import FLOPS_BACKEND, get_model_complexity_info
>   File "/home/limingbo/.local/lib/python3.7/site-packages/ptflops/flops_counter.py", line 15, in <module>
>     from .aten_engine import get_flops_aten
>   File "/home/limingbo/.local/lib/python3.7/site-packages/ptflops/aten_engine.py", line 17, in <module>
>     from torch.utils._python_dispatch import TorchDispatchMode
> ModuleNotFoundError: No module named 'torch.utils._python_dispatch'

In fact, this problem can be solved with the following command：
```bash
pip install ptflops==0.7.2.2
```
Ref to [https://blog.csdn.net/qq_43298381/article/details/143062160](https://blog.csdn.net/qq_43298381/article/details/143062160)
